language: go
go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - "master"
matrix:
  allow_failures:
    - go: master
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
