language: go
go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - "master"
matrix:
  allow_failures:
    - go: master
before_script:
  - go get -u github.com/AlekSi/gocoverutil
script:
  - gocoverutil test -v ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
